server:
    port: 8080
    shutdown: graceful
    servlet:
      session:
        timeout: 10

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: first-serivce
          uri: http://naver.com:80
          predicates:
            - Path= */*